dtcenter/METexpress

.readthedocs.yaml
docs/requirements.txt

Set up ReadTheDocs for MET and verified everything looked good here:
https://metexpress.readthedocs.io/en/feature_15_readthedocs/
Review the "Files Changed" and look at the webpage above and let me know if you see anything that needs modifications.
I do not believe I have the authority to merge here, but I am not sure.  Could you please also merge it?  
Redirection and documentation, including updating the Release Guide, will be done later.
dtcenter/METplus#836
See the [METplus Workflow](https://dtcenter.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
Select: **Reviewer(s)**, **Project(s)** (there was no appropriate project for me to select), and **Milestone**

feature_15_readthedocs

---

.github/jobs/build_documentation.sh
.github/workflows/main.yml
.readthedocs.yaml
docs/Makefile
docs/conf.py

Verified GitHub actions runs and generates a warning log file.
Verify GitHub actions ran and generated a warning log file.
See the [METplus Workflow](https://dtcenter.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
Select: **Reviewer(s)**, **Project(s)**, and **Milestone**

Feature GitHub actions doc

---

docs/Users_Guide/index.rst
docs/index.rst

Only documentation changes, mostly about the authorship list.
No testing, just review the doc changes.
None needed
See the [METplus Workflow](https://dtcenter.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
Select: **Reviewer(s)**, **Project(s)**, and **Milestone**

Feature authorship

---

apps/met-tc/server/dataFunctions/data_dieoff.js
apps/met-tc/server/dataFunctions/data_histogram.js
apps/met-tc/server/dataFunctions/data_series.js
apps/met-tc/server/dataFunctions/data_validtime.js
apps/met-tc/server/dataFunctions/data_yeartoyear.js
apps/met-tc/server/main.js
scripts/matsMetaDataForApps/createMetaData/mysql/metexpress/MEmetadata.py
scripts/matsMetaDataForApps/createMetaData/mysql/metexpress/MEmetadata_update.py

Changes to MET TC app so it can support ECs.

Feature molly workspace

---

.github/workflows/prune-pr-images.yml

Github Actions if statement may be taking the quotes literally which
could be the reason the if statement isn't working as expected.
Closes #53

Remove quotes from the branch name

---

.github/workflows/prune-untagged-images.yml

Test whether Github Actions `if` statements evaluate quotations literally.

Bring CI changes to main

---

.github/workflows/prune-pr-images.yml

The docs make it sound like expression syntax can be omitted in an if statement. Maybe having the syntax confuses Actions?
https://docs.github.com/en/actions/learn-github-actions/expressions#about-expressions

More attempts at getting the if syntax correct

---

.github/workflows/prune-pr-images.yml

Bring syntax test to main

---

tests/package-lock.json
tests/package.json

This pull request is for the Python ctc errorbar code and the JavaScript interface to talk to it. It also includes chromedriver updates for out automated tests.

Feature ctc matching errorbars

---

apps/met-airquality/.meteor/packages
apps/met-airquality/.meteor/release
apps/met-airquality/.meteor/versions
apps/met-airquality/package-lock.json
apps/met-anomalycor/.meteor/packages
apps/met-anomalycor/.meteor/release
apps/met-anomalycor/.meteor/versions
apps/met-anomalycor/package-lock.json
apps/met-cyclone/.meteor/packages
apps/met-cyclone/.meteor/release
apps/met-cyclone/.meteor/versions
apps/met-cyclone/package-lock.json
apps/met-ensemble/.meteor/packages
apps/met-ensemble/.meteor/release
apps/met-ensemble/.meteor/versions
apps/met-ensemble/package-lock.json
apps/met-precip/.meteor/packages
apps/met-precip/.meteor/release
apps/met-precip/.meteor/versions
apps/met-precip/package-lock.json
apps/met-surface/.meteor/packages
apps/met-surface/.meteor/release
apps/met-surface/.meteor/versions
apps/met-surface/package-lock.json
apps/met-upperair/.meteor/packages
apps/met-upperair/.meteor/release
apps/met-upperair/.meteor/versions
apps/met-upperair/package-lock.json

Initial merge of cb-ceiling code

Cb ceiling

---

Dockerfile
apps/met-airquality/package-lock.json
apps/met-airquality/package.json
apps/met-anomalycor/package-lock.json
apps/met-anomalycor/package.json
apps/met-cyclone/package-lock.json
apps/met-cyclone/package.json
apps/met-ensemble/package-lock.json
apps/met-ensemble/package.json
apps/met-precip/package-lock.json
apps/met-precip/package.json
apps/met-surface/package-lock.json
apps/met-surface/package.json
apps/met-upperair/package-lock.json
apps/met-upperair/package.json

Updated jspdf version in METexpress package.json files. The pull request which correctly wants to merge to development, not main.

Feature update jspdf

---

apps/met-airquality/public/title
apps/met-anomalycor/public/title
apps/met-cyclone/public/title
apps/met-ensemble/public/title
apps/met-precip/public/title
apps/met-surface/public/title
apps/met-upperair/public/title

METexpress pull request for collapsing the ceiling and visibility apps into one.

Feature combine ceil vis

---

.github/workflows/deploy.yml

Whitespace isn't valid in an `${ENV}` block. Also, remove the leading `refs/tags/` as we don't want that in our image tags.

Fix deploy action syntax

---

.github/workflows/build.yml
.github/workflows/codeql-analysis.yml
.github/workflows/documentation.yml
.github/workflows/trivy-repo-analysis.yml

Verify no warnings from GHA
For the following files:
build.yml codeql-analysis.yml documentation.yml trivy-repo-analysis.yml 
verify that version numbers updated (wherever applicable):
- Update version of actions/checkout to v3
- Update version of actions/setup-python to v4
- Update version of actions/upload-artifact to v3
- Update version of actions/download-artifact to v3
- Update version of actions/github-script to v6
Select: **Milestone** as the …

Issue #99 update versions

---

LICENSE.md

Adding a License file to the repo.

Feature 113 main v5.0 license

---

LICENSE.md

Adding LICENSE.md file to develop

Feature 113 develop license

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/enhancement_request.md
.github/ISSUE_TEMPLATE/new_feature_request.md
.github/ISSUE_TEMPLATE/sub-issue.md
.github/ISSUE_TEMPLATE/task.md

Feature development cycle change

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/enhancement_request.md
.github/ISSUE_TEMPLATE/new_feature_request.md
.github/ISSUE_TEMPLATE/sub-issue.md
.github/ISSUE_TEMPLATE/task.md

Feature main cycle change

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/enhancement_request.md
.github/ISSUE_TEMPLATE/new_feature_request.md
.github/ISSUE_TEMPLATE/sub-issue.md
.github/ISSUE_TEMPLATE/task.md
.github/pull_request_template.md

Reviewed the changes.  These changes are based off of the work from this [MET issue](https://github.com/dtcenter/MET/issues/2659) to improve the issue and pull request templates.  
Review the changes.
If **yes**, please describe:

Feature 139 development update templates

---

apps/met-cyclone/server/dataFunctions/data_dieoff.js
apps/met-cyclone/server/dataFunctions/data_histogram.js
apps/met-cyclone/server/dataFunctions/data_series.js
apps/met-cyclone/server/dataFunctions/data_validtime.js
apps/met-cyclone/server/dataFunctions/data_yeartoyear.js
apps/met-cyclone/server/main.js
scripts/matsMetaDataForApps/createMetaData/mysql/metexpress/MEcyclone.py
scripts/matsMetaDataForApps/createMetaData/mysql/metexpress/MEcycloneRI.py

This PR adds the ability to plot RI CTC statistics to the MET Cyclone app.

Add RI verification to the MET Cyclone app

---

.github/workflows/build.yml
Dockerfile

Updates CI & our container image for Meteor 3. Key changes:
* Update the Docker Meteor image used in the Dockerfile to match the application version of Meteor
* Update various Docker Node images to Node 22
* Install our runtime Python dependencies in a virtual environment

Update Container & CI for Meteor 3
